# Generated by Django 4.2.2 on 2023-06-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0453_followed_topic_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedattachment",
            name="file_id",
            field=models.UUIDField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="file_id",
            field=models.UUIDField(db_index=True, null=True, unique=True),
        ),
    ]
